# Generated by Django 4.1.3 on 2023-01-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
